// Generated by scripts/generate-openapi-schemas.ts. Do not edit manually.

export const generatedOpenApiSchemas = {
    "ClanEventsDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "gameId": {
                "anyOf": [
                    {
                        "const": "hell_let_loose"
                    },
                    {
                        "const": "hell_let_loose_vietnam"
                    },
                    {
                        "const": "wardogs"
                    }
                ]
            },
            "kind": {
                "anyOf": [
                    {
                        "const": "match"
                    },
                    {
                        "const": "training"
                    }
                ]
            },
            "matchType": {
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "thumbnailUrl": {
                "type": "string"
            },
            "imageUrl": {
                "type": "string"
            },
            "announcementChannelId": {
                "type": "string"
            },
            "eventInfoChannelId": {
                "type": "string"
            },
            "meetingChannelId": {
                "type": "string"
            },
            "requiredRoleIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "rewardRoleIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "signupGroupIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "allowedSignupStatuses": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "const": "recruit"
                        },
                        {
                            "const": "member"
                        },
                        {
                            "const": "reserve_member"
                        },
                        {
                            "const": "mercenary"
                        }
                    ]
                }
            },
            "useGeneralSignup": {
                "type": "boolean"
            },
            "signupReminderStatuses": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "const": "recruit"
                        },
                        {
                            "const": "member"
                        },
                        {
                            "const": "reserve_member"
                        }
                    ]
                }
            },
            "recurrence": {
                "type": "object",
                "properties": {
                    "frequency": {
                        "anyOf": [
                            {
                                "const": "weekly"
                            },
                            {
                                "const": "monthly_date"
                            },
                            {
                                "const": "monthly_nth_weekday"
                            }
                        ]
                    },
                    "interval": {
                        "type": "number"
                    },
                    "weekdays": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "monthDay": {
                        "type": "number"
                    },
                    "nth": {
                        "type": "number"
                    },
                    "weekday": {
                        "type": "number"
                    }
                },
                "required": [
                    "frequency",
                    "interval",
                    "weekdays"
                ]
            },
            "attendeeRoleId": {
                "type": "string"
            },
            "reserveRoleId": {
                "type": "string"
            },
            "server": {
                "type": "string"
            },
            "serverPassword": {
                "type": "string"
            },
            "side": {
                "type": "string"
            },
            "map": {
                "type": "string"
            },
            "cap": {
                "type": "string"
            },
            "notes": {
                "type": "string"
            },
            "registrationEnd": {
                "type": "string"
            },
            "meetingStart": {
                "type": "string"
            },
            "gameStart": {
                "type": "string"
            },
            "gameEnd": {
                "type": "string"
            },
            "pingClan": {
                "type": "boolean"
            },
            "pingMode": {
                "anyOf": [
                    {
                        "const": "none"
                    },
                    {
                        "const": "clan"
                    },
                    {
                        "const": "roles"
                    }
                ]
            },
            "pingRoleIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "createForumChannel": {
                "type": "boolean"
            },
            "topicPresetId": {
                "type": "string",
                "description": "Convex ID for topicPresets"
            },
            "stratmapIds": {
                "type": "array",
                "items": {
                    "type": "string",
                    "description": "Convex ID for stratmaps"
                }
            },
            "status": {
                "anyOf": [
                    {
                        "const": "registration"
                    },
                    {
                        "const": "closed"
                    },
                    {
                        "const": "starting"
                    },
                    {
                        "const": "concluded"
                    }
                ]
            },
            "statusUpdatedAt": {
                "type": "string"
            },
            "concludedAt": {
                "type": "string"
            },
            "eventResult": {
                "type": "object",
                "properties": {
                    "sourceUrl": {
                        "type": "string"
                    },
                    "mapId": {
                        "type": "string"
                    },
                    "mapName": {
                        "type": "string"
                    },
                    "endedAt": {
                        "type": "string"
                    },
                    "importedAt": {
                        "type": "string"
                    },
                    "sideA": {
                        "type": "string"
                    },
                    "sideB": {
                        "type": "string"
                    },
                    "outcome": {
                        "anyOf": [
                            {
                                "const": "victory"
                            },
                            {
                                "const": "defeat"
                            },
                            {
                                "const": "draw"
                            }
                        ]
                    },
                    "score": {
                        "type": "object",
                        "properties": {
                            "sideA": {
                                "type": "number"
                            },
                            "sideB": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "sideA",
                            "sideB"
                        ]
                    }
                },
                "required": [
                    "sourceUrl",
                    "mapId",
                    "importedAt",
                    "sideA",
                    "sideB",
                    "outcome",
                    "score"
                ]
            },
            "matchStatsId": {
                "type": "string",
                "description": "Convex ID for matchStats"
            },
            "competitionFixtureId": {
                "type": "string",
                "description": "Convex ID for competitionFixtures"
            },
            "attendanceReminderLog": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string"
                        },
                        "offsetHours": {
                            "type": "number"
                        },
                        "sentAt": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "userId",
                        "offsetHours",
                        "sentAt"
                    ]
                }
            },
            "participants": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string"
                        },
                        "status": {
                            "anyOf": [
                                {
                                    "const": "attending"
                                },
                                {
                                    "const": "not_attending"
                                }
                            ]
                        },
                        "group": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "null"
                                }
                            ]
                        },
                        "completed": {
                            "anyOf": [
                                {
                                    "const": "passed"
                                },
                                {
                                    "const": "failed"
                                }
                            ]
                        },
                        "updatedAt": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "userId",
                        "status",
                        "updatedAt"
                    ]
                }
            },
            "signUps": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string"
                        },
                        "group": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "null"
                                }
                            ]
                        }
                    },
                    "required": [
                        "userId"
                    ]
                }
            },
            "scoreAppliedAt": {
                "type": "string"
            },
            "scoreResolution": {
                "anyOf": [
                    {
                        "const": "applied"
                    },
                    {
                        "const": "skipped"
                    }
                ]
            },
            "absenceNotices": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string"
                        },
                        "reason": {
                            "type": "string"
                        },
                        "createdAt": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "userId",
                        "reason",
                        "createdAt"
                    ]
                }
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "name",
            "registrationEnd",
            "meetingStart",
            "gameStart",
            "gameEnd",
            "pingClan",
            "createdAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "gameId": "hell_let_loose",
            "kind": "match",
            "matchType": "string",
            "name": "string",
            "description": "string",
            "thumbnailUrl": "string",
            "imageUrl": "string",
            "announcementChannelId": "string",
            "eventInfoChannelId": "string",
            "meetingChannelId": "string",
            "requiredRoleIds": [
                "string"
            ],
            "rewardRoleIds": [
                "string"
            ],
            "signupGroupIds": [
                "string"
            ],
            "allowedSignupStatuses": [
                "recruit"
            ],
            "useGeneralSignup": true,
            "signupReminderStatuses": [
                "recruit"
            ],
            "recurrence": {
                "frequency": "weekly",
                "interval": 0,
                "weekdays": [
                    0
                ],
                "monthDay": 0,
                "nth": 0,
                "weekday": 0
            },
            "attendeeRoleId": "string",
            "reserveRoleId": "string",
            "server": "string",
            "serverPassword": "string",
            "side": "string",
            "map": "string",
            "cap": "string",
            "notes": "string",
            "registrationEnd": "string",
            "meetingStart": "string",
            "gameStart": "string",
            "gameEnd": "string",
            "pingClan": true,
            "pingMode": "none",
            "pingRoleIds": [
                "string"
            ],
            "createForumChannel": true,
            "topicPresetId": "string",
            "stratmapIds": [
                "string"
            ],
            "status": "registration",
            "statusUpdatedAt": "string",
            "concludedAt": "string",
            "eventResult": {
                "sourceUrl": "string",
                "mapId": "string",
                "mapName": "string",
                "endedAt": "string",
                "importedAt": "string",
                "sideA": "string",
                "sideB": "string",
                "outcome": "victory",
                "score": {
                    "sideA": 0,
                    "sideB": 0
                }
            },
            "matchStatsId": "string",
            "competitionFixtureId": "string",
            "attendanceReminderLog": [
                {
                    "userId": "string",
                    "offsetHours": 0,
                    "sentAt": "string"
                }
            ],
            "participants": [
                {
                    "userId": "string",
                    "status": "attending",
                    "group": "string",
                    "completed": "passed",
                    "updatedAt": "string"
                }
            ],
            "signUps": [
                {
                    "userId": "string",
                    "group": "string"
                }
            ],
            "scoreAppliedAt": "string",
            "scoreResolution": "applied",
            "absenceNotices": [
                {
                    "userId": "string",
                    "reason": "string",
                    "createdAt": "string"
                }
            ],
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanGroupsDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "gameId": {
                "anyOf": [
                    {
                        "const": "hell_let_loose"
                    },
                    {
                        "const": "hell_let_loose_vietnam"
                    },
                    {
                        "const": "wardogs"
                    }
                ]
            },
            "name": {
                "type": "string"
            },
            "color": {
                "type": "string"
            },
            "order": {
                "type": "number"
            },
            "parentId": {
                "type": "string",
                "description": "Convex ID for groups"
            },
            "description": {
                "type": "string"
            },
            "discordRoleId": {
                "type": "string"
            },
            "discordEmoji": {
                "type": "string"
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "name",
            "color",
            "order",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "gameId": "hell_let_loose",
            "name": "string",
            "color": "string",
            "order": 0,
            "parentId": "string",
            "description": "string",
            "discordRoleId": "string",
            "discordEmoji": "string",
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanRostersDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "eventId": {
                "type": "string",
                "description": "Convex ID for events"
            },
            "squadPresetId": {
                "type": "string",
                "description": "Convex ID for squadPresets"
            },
            "squads": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "group": {
                            "type": "string"
                        },
                        "order": {
                            "type": "number"
                        },
                        "color": {
                            "type": "string"
                        },
                        "icon": {
                            "type": "string"
                        },
                        "players": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "string"
                                    },
                                    "customName": {
                                        "type": "string"
                                    },
                                    "ack": {
                                        "type": "boolean"
                                    },
                                    "confirmed": {
                                        "type": "boolean"
                                    },
                                    "note": {
                                        "type": "string"
                                    },
                                    "roleName": {
                                        "type": "string"
                                    },
                                    "roleIcon": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "ack"
                                ]
                            }
                        }
                    },
                    "required": [
                        "name",
                        "group",
                        "order",
                        "color",
                        "players"
                    ]
                }
            },
            "reservePlayerIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "reserveAttendances": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string"
                        },
                        "ack": {
                            "type": "boolean"
                        },
                        "confirmed": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "userId",
                        "ack"
                    ]
                }
            },
            "notAttendingPlayerIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "streamerId": {
                "type": "string"
            },
            "published": {
                "type": "boolean"
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "eventId",
            "squads",
            "reservePlayerIds",
            "notAttendingPlayerIds",
            "published",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "eventId": "string",
            "squadPresetId": "string",
            "squads": [
                {
                    "name": "string",
                    "group": "string",
                    "order": 0,
                    "color": "string",
                    "icon": "string",
                    "players": [
                        {
                            "id": "string",
                            "customName": "string",
                            "ack": true,
                            "confirmed": true,
                            "note": "string",
                            "roleName": "string",
                            "roleIcon": "string"
                        }
                    ]
                }
            ],
            "reservePlayerIds": [
                "string"
            ],
            "reserveAttendances": [
                {
                    "userId": "string",
                    "ack": true,
                    "confirmed": true
                }
            ],
            "notAttendingPlayerIds": [
                "string"
            ],
            "streamerId": "string",
            "published": true,
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanAssignmentsDocument": {
        "type": "object",
        "properties": {
            "userId": {
                "type": "string"
            },
            "serverId": {
                "type": "string"
            },
            "gameId": {
                "anyOf": [
                    {
                        "const": "hell_let_loose"
                    },
                    {
                        "const": "hell_let_loose_vietnam"
                    },
                    {
                        "const": "wardogs"
                    }
                ]
            },
            "type": {
                "anyOf": [
                    {
                        "const": "member"
                    },
                    {
                        "const": "reserve_member"
                    },
                    {
                        "const": "mercenary"
                    }
                ]
            },
            "status": {
                "anyOf": [
                    {
                        "const": "pending"
                    },
                    {
                        "const": "recruit"
                    },
                    {
                        "const": "active"
                    }
                ]
            },
            "membershipCategoryId": {
                "type": "string"
            },
            "primaryGroupId": {
                "type": "string",
                "description": "Convex ID for groups"
            },
            "secondaryGroupIds": {
                "type": "array",
                "items": {
                    "type": "string",
                    "description": "Convex ID for groups"
                }
            },
            "group": {
                "type": "string"
            },
            "paused": {
                "type": "boolean"
            },
            "pausedNote": {
                "type": "string"
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "userId",
            "serverId",
            "type",
            "status",
            "paused",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "userId": "string",
            "serverId": "string",
            "gameId": "hell_let_loose",
            "type": "member",
            "status": "pending",
            "membershipCategoryId": "string",
            "primaryGroupId": "string",
            "secondaryGroupIds": [
                "string"
            ],
            "group": "string",
            "paused": true,
            "pausedNote": "string",
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanCalendarItemsDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "title": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "color": {
                "type": "string"
            },
            "emoji": {
                "type": "string"
            },
            "label": {
                "type": "string"
            },
            "startAt": {
                "type": "string"
            },
            "endAt": {
                "type": "string"
            },
            "allDay": {
                "type": "boolean"
            },
            "recurrence": {
                "type": "object",
                "properties": {
                    "frequency": {
                        "anyOf": [
                            {
                                "const": "weekly"
                            },
                            {
                                "const": "monthly_date"
                            },
                            {
                                "const": "monthly_nth_weekday"
                            },
                            {
                                "const": "yearly"
                            }
                        ]
                    },
                    "interval": {
                        "type": "number"
                    },
                    "until": {
                        "type": "string"
                    }
                },
                "required": [
                    "frequency",
                    "interval"
                ]
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "title",
            "color",
            "startAt",
            "endAt",
            "allDay",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "title": "string",
            "description": "string",
            "color": "string",
            "emoji": "string",
            "label": "string",
            "startAt": "string",
            "endAt": "string",
            "allDay": true,
            "recurrence": {
                "frequency": "weekly",
                "interval": 0,
                "until": "string"
            },
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanStratmapsDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "gameId": {
                "anyOf": [
                    {
                        "const": "hell_let_loose"
                    },
                    {
                        "const": "hell_let_loose_vietnam"
                    },
                    {
                        "const": "wardogs"
                    }
                ]
            },
            "eventId": {
                "type": "string",
                "description": "Convex ID for events"
            },
            "title": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "baseMapId": {
                "type": "string"
            },
            "side": {
                "type": "string"
            },
            "strongpointId": {
                "type": "string"
            },
            "state": {
                "type": "string"
            },
            "createdBy": {
                "type": "string"
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "title",
            "baseMapId",
            "state",
            "createdBy",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "gameId": "hell_let_loose",
            "eventId": "string",
            "title": "string",
            "description": "string",
            "baseMapId": "string",
            "side": "string",
            "strongpointId": "string",
            "state": "string",
            "createdBy": "string",
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanTopicPresetsDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "side": {
                "type": "string"
            },
            "map": {
                "type": "string"
            },
            "cap": {
                "type": "string"
            },
            "notes": {
                "type": "string"
            },
            "topics": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "messages": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "string"
                                    },
                                    "body": {
                                        "type": "string"
                                    },
                                    "attachments": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "required": [
                                    "id",
                                    "attachments"
                                ]
                            }
                        },
                        "body": {
                            "type": "string"
                        },
                        "attachments": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "required": [
                        "title",
                        "attachments"
                    ]
                }
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "name",
            "topics",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "name": "string",
            "side": "string",
            "map": "string",
            "cap": "string",
            "notes": "string",
            "topics": [
                {
                    "id": "string",
                    "title": "string",
                    "messages": [
                        {
                            "id": "string",
                            "body": "string",
                            "attachments": [
                                "string"
                            ]
                        }
                    ],
                    "body": "string",
                    "attachments": [
                        "string"
                    ]
                }
            ],
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanSquadPresetsDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "squads": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "group": {
                            "type": "string"
                        },
                        "order": {
                            "type": "number"
                        },
                        "color": {
                            "type": "string"
                        },
                        "icon": {
                            "type": "string"
                        },
                        "roles": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "color": {
                                        "type": "string"
                                    },
                                    "icon": {
                                        "type": "string"
                                    },
                                    "count": {
                                        "type": "number"
                                    },
                                    "note": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "name",
                                    "color",
                                    "icon",
                                    "count"
                                ]
                            }
                        }
                    },
                    "required": [
                        "name",
                        "group",
                        "order",
                        "color",
                        "icon",
                        "roles"
                    ]
                }
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "name",
            "squads",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "name": "string",
            "squads": [
                {
                    "name": "string",
                    "group": "string",
                    "order": 0,
                    "color": "string",
                    "icon": "string",
                    "roles": [
                        {
                            "name": "string",
                            "color": "string",
                            "icon": "string",
                            "count": 0,
                            "note": "string"
                        }
                    ]
                }
            ],
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanMatchesDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "gameId": {
                "anyOf": [
                    {
                        "const": "hell_let_loose"
                    },
                    {
                        "const": "hell_let_loose_vietnam"
                    },
                    {
                        "const": "wardogs"
                    }
                ]
            },
            "eventId": {
                "type": "string",
                "description": "Convex ID for events"
            },
            "sourceUrl": {
                "type": "string"
            },
            "matchId": {
                "type": "string"
            },
            "importedAt": {
                "type": "string"
            },
            "raw": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "creation_time": {
                        "type": "string"
                    },
                    "start": {
                        "type": "string"
                    },
                    "end": {
                        "type": "string"
                    },
                    "server_number": {
                        "type": "number"
                    },
                    "map_name": {
                        "type": "string"
                    },
                    "result": {
                        "type": "object",
                        "properties": {
                            "axis": {
                                "type": "number"
                            },
                            "allied": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "axis",
                            "allied"
                        ]
                    },
                    "game_layout": {
                        "type": "object",
                        "properties": {
                            "requested": {
                                "type": "array",
                                "items": {
                                    "anyOf": [
                                        {
                                            "type": "number"
                                        },
                                        {
                                            "type": "null"
                                        }
                                    ]
                                }
                            },
                            "set": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": [
                            "requested",
                            "set"
                        ]
                    },
                    "cap_flips": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "allied_score": {
                                    "type": "number"
                                },
                                "axis_score": {
                                    "type": "number"
                                },
                                "ts": {
                                    "type": "number"
                                }
                            },
                            "required": [
                                "allied_score",
                                "axis_score",
                                "ts"
                            ]
                        }
                    },
                    "match_time": {
                        "type": "number"
                    },
                    "player_stats": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "number"
                                },
                                "player_id": {
                                    "type": "string"
                                },
                                "player": {
                                    "type": "string"
                                },
                                "map_id": {
                                    "type": "number"
                                },
                                "kills": {
                                    "type": "number"
                                },
                                "kills_by_type": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                },
                                "kills_streak": {
                                    "type": "number"
                                },
                                "deaths": {
                                    "type": "number"
                                },
                                "deaths_by_type": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                },
                                "deaths_without_kill_streak": {
                                    "type": "number"
                                },
                                "teamkills": {
                                    "type": "number"
                                },
                                "teamkills_streak": {
                                    "type": "number"
                                },
                                "deaths_by_tk": {
                                    "type": "number"
                                },
                                "deaths_by_tk_streak": {
                                    "type": "number"
                                },
                                "nb_vote_started": {
                                    "type": "number"
                                },
                                "nb_voted_yes": {
                                    "type": "number"
                                },
                                "nb_voted_no": {
                                    "type": "number"
                                },
                                "time_seconds": {
                                    "type": "number"
                                },
                                "kills_per_minute": {
                                    "type": "number"
                                },
                                "deaths_per_minute": {
                                    "type": "number"
                                },
                                "kill_death_ratio": {
                                    "type": "number"
                                },
                                "longest_life_secs": {
                                    "type": "number"
                                },
                                "shortest_life_secs": {
                                    "type": "number"
                                },
                                "combat": {
                                    "type": "number"
                                },
                                "offense": {
                                    "type": "number"
                                },
                                "defense": {
                                    "type": "number"
                                },
                                "support": {
                                    "type": "number"
                                },
                                "most_killed": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                },
                                "death_by": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                },
                                "weapons": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                },
                                "death_by_weapons": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                },
                                "team": {
                                    "type": "object",
                                    "properties": {
                                        "side": {
                                            "type": "string"
                                        },
                                        "confidence": {
                                            "anyOf": [
                                                {
                                                    "const": "strong"
                                                },
                                                {
                                                    "const": "mixed"
                                                }
                                            ]
                                        },
                                        "ratio": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "side"
                                    ]
                                },
                                "level": {
                                    "type": "number"
                                },
                                "platform": {
                                    "type": "string"
                                },
                                "steaminfo": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "number"
                                        },
                                        "created": {
                                            "type": "string"
                                        },
                                        "updated": {
                                            "anyOf": [
                                                {
                                                    "type": "string"
                                                },
                                                {
                                                    "type": "null"
                                                }
                                            ]
                                        },
                                        "profile": {
                                            "anyOf": [
                                                {
                                                    "type": "string"
                                                },
                                                {
                                                    "type": "null"
                                                }
                                            ]
                                        },
                                        "country": {
                                            "anyOf": [
                                                {
                                                    "type": "string"
                                                },
                                                {
                                                    "type": "null"
                                                }
                                            ]
                                        },
                                        "bans": {
                                            "anyOf": [
                                                {
                                                    "type": "number"
                                                },
                                                {
                                                    "type": "null"
                                                }
                                            ]
                                        },
                                        "has_bans": {
                                            "type": "boolean"
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "created",
                                        "updated",
                                        "profile",
                                        "country",
                                        "bans",
                                        "has_bans"
                                    ]
                                },
                                "vehicle_kills": {
                                    "type": "number"
                                },
                                "vehicles_destroyed": {
                                    "type": "number"
                                },
                                "kills_and_assists": {
                                    "type": "number"
                                },
                                "deaths_and_redeploys": {
                                    "type": "number"
                                },
                                "units": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "ts": {
                                                "type": "number"
                                            },
                                            "team": {
                                                "type": "number"
                                            },
                                            "squad": {
                                                "type": "number"
                                            },
                                            "role": {
                                                "type": "number"
                                            }
                                        },
                                        "required": [
                                            "ts",
                                            "team",
                                            "squad",
                                            "role"
                                        ]
                                    }
                                },
                                "encounters": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "action": {
                                                "type": "string"
                                            },
                                            "player_id": {
                                                "type": "string"
                                            },
                                            "player_name": {
                                                "type": "string"
                                            },
                                            "ts": {
                                                "type": "number"
                                            },
                                            "weapon": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "action",
                                            "player_id",
                                            "player_name",
                                            "ts",
                                            "weapon"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "id",
                                "player_id",
                                "player",
                                "map_id",
                                "kills",
                                "kills_streak",
                                "deaths",
                                "deaths_without_kill_streak",
                                "teamkills",
                                "teamkills_streak",
                                "deaths_by_tk",
                                "deaths_by_tk_streak",
                                "nb_vote_started",
                                "nb_voted_yes",
                                "nb_voted_no",
                                "time_seconds",
                                "kills_per_minute",
                                "deaths_per_minute",
                                "kill_death_ratio",
                                "longest_life_secs",
                                "shortest_life_secs",
                                "combat",
                                "offense",
                                "defense",
                                "support",
                                "most_killed",
                                "death_by",
                                "weapons",
                                "death_by_weapons",
                                "team",
                                "level"
                            ]
                        }
                    },
                    "map": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "game_mode": {
                                "type": "string"
                            },
                            "attackers": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                            },
                            "environment": {
                                "type": "string"
                            },
                            "pretty_name": {
                                "type": "string"
                            },
                            "image_name": {
                                "type": "string"
                            },
                            "map": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "tag": {
                                        "type": "string"
                                    },
                                    "pretty_name": {
                                        "type": "string"
                                    },
                                    "shortname": {
                                        "type": "string"
                                    },
                                    "allies": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "team": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "name",
                                            "team"
                                        ]
                                    },
                                    "axis": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "team": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "name",
                                            "team"
                                        ]
                                    },
                                    "orientation": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "id",
                                    "name",
                                    "tag",
                                    "pretty_name",
                                    "shortname",
                                    "allies",
                                    "axis",
                                    "orientation"
                                ]
                            }
                        },
                        "required": [
                            "id",
                            "game_mode",
                            "environment",
                            "pretty_name",
                            "image_name",
                            "map"
                        ]
                    }
                },
                "required": [
                    "id",
                    "creation_time",
                    "start",
                    "end",
                    "server_number",
                    "map_name",
                    "result",
                    "game_layout",
                    "player_stats",
                    "map"
                ]
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "eventId",
            "sourceUrl",
            "matchId",
            "importedAt",
            "raw",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "gameId": "hell_let_loose",
            "eventId": "string",
            "sourceUrl": "string",
            "matchId": "string",
            "importedAt": "string",
            "raw": {
                "id": 0,
                "creation_time": "string",
                "start": "string",
                "end": "string",
                "server_number": 0,
                "map_name": "string",
                "result": {
                    "axis": 0,
                    "allied": 0
                },
                "game_layout": {
                    "requested": [
                        0
                    ],
                    "set": [
                        "string"
                    ]
                },
                "cap_flips": [
                    {
                        "allied_score": 0,
                        "axis_score": 0,
                        "ts": 0
                    }
                ],
                "match_time": 0,
                "player_stats": [
                    {
                        "id": 0,
                        "player_id": "string",
                        "player": "string",
                        "map_id": 0,
                        "kills": 0,
                        "kills_by_type": {
                            "key": 0
                        },
                        "kills_streak": 0,
                        "deaths": 0,
                        "deaths_by_type": {
                            "key": 0
                        },
                        "deaths_without_kill_streak": 0,
                        "teamkills": 0,
                        "teamkills_streak": 0,
                        "deaths_by_tk": 0,
                        "deaths_by_tk_streak": 0,
                        "nb_vote_started": 0,
                        "nb_voted_yes": 0,
                        "nb_voted_no": 0,
                        "time_seconds": 0,
                        "kills_per_minute": 0,
                        "deaths_per_minute": 0,
                        "kill_death_ratio": 0,
                        "longest_life_secs": 0,
                        "shortest_life_secs": 0,
                        "combat": 0,
                        "offense": 0,
                        "defense": 0,
                        "support": 0,
                        "most_killed": {
                            "key": 0
                        },
                        "death_by": {
                            "key": 0
                        },
                        "weapons": {
                            "key": 0
                        },
                        "death_by_weapons": {
                            "key": 0
                        },
                        "team": {
                            "side": "string",
                            "confidence": "strong",
                            "ratio": 0
                        },
                        "level": 0,
                        "platform": "string",
                        "steaminfo": {
                            "id": 0,
                            "created": "string",
                            "updated": "string",
                            "profile": "string",
                            "country": "string",
                            "bans": 0,
                            "has_bans": true
                        },
                        "vehicle_kills": 0,
                        "vehicles_destroyed": 0,
                        "kills_and_assists": 0,
                        "deaths_and_redeploys": 0,
                        "units": [
                            {
                                "ts": 0,
                                "team": 0,
                                "squad": 0,
                                "role": 0
                            }
                        ],
                        "encounters": [
                            {
                                "action": "string",
                                "player_id": "string",
                                "player_name": "string",
                                "ts": 0,
                                "weapon": "string"
                            }
                        ]
                    }
                ],
                "map": {
                    "id": "string",
                    "game_mode": "string",
                    "attackers": "string",
                    "environment": "string",
                    "pretty_name": "string",
                    "image_name": "string",
                    "map": {
                        "id": "string",
                        "name": "string",
                        "tag": "string",
                        "pretty_name": "string",
                        "shortname": "string",
                        "allies": {
                            "name": "string",
                            "team": "string"
                        },
                        "axis": {
                            "name": "string",
                            "team": "string"
                        },
                        "orientation": "string"
                    }
                }
            },
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanArticlesDocument": {
        "type": "object",
        "properties": {
            "guildId": {
                "type": "string"
            },
            "title": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "tags": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "body": {
                "type": "string"
            },
            "attachments": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "authorId": {
                "type": "string"
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            }
        },
        "required": [
            "guildId",
            "title",
            "description",
            "tags",
            "body",
            "attachments",
            "authorId",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "guildId": "string",
            "title": "string",
            "description": "string",
            "tags": [
                "string"
            ],
            "body": "string",
            "attachments": [
                "string"
            ],
            "authorId": "string",
            "createdAt": "string",
            "updatedAt": "string",
            "id": "string"
        }
    },
    "ClanUsersDocument": {
        "type": "object",
        "properties": {
            "discordId": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "description": "Opaque resource ID."
            },
            "name": {
                "type": "string"
            },
            "note": {
                "type": "string"
            },
            "nicknames": {
                "type": "object",
                "additionalProperties": {
                    "type": "string"
                }
            },
            "platformIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "avatar": {
                "type": "string"
            },
            "managedGuildIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "guildId": {
                "type": "string"
            },
            "defaultWorkspaceId": {
                "type": "string"
            },
            "defaultWorkspaceRecordId": {
                "type": "string"
            },
            "mercenaryGuildIds": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "isStreamer": {
                "type": "boolean"
            },
            "matchRecapNotificationsEnabled": {
                "type": "boolean"
            },
            "score": {
                "type": "number"
            },
            "scores": {
                "type": "object",
                "additionalProperties": {
                    "type": "number"
                }
            },
            "performance": {
                "type": "object",
                "properties": {
                    "matchesPlayed": {
                        "type": "number"
                    },
                    "averages": {
                        "type": "object",
                        "properties": {
                            "kills": {
                                "type": "number"
                            },
                            "killDeathRatio": {
                                "type": "number"
                            },
                            "deaths": {
                                "type": "number"
                            },
                            "offense": {
                                "type": "number"
                            },
                            "defense": {
                                "type": "number"
                            },
                            "support": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "kills",
                            "killDeathRatio",
                            "deaths",
                            "offense",
                            "defense",
                            "support"
                        ]
                    }
                },
                "required": [
                    "matchesPlayed",
                    "averages"
                ]
            },
            "onboarding": {
                "type": "object",
                "properties": {
                    "dashboardSetupCompletedAt": {
                        "type": "string"
                    },
                    "workspaceTourCompletedAt": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                }
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            }
        },
        "required": [
            "name",
            "avatar",
            "managedGuildIds",
            "mercenaryGuildIds",
            "isStreamer",
            "createdAt",
            "updatedAt",
            "id"
        ],
        "example": {
            "discordId": "string",
            "id": "string",
            "name": "string",
            "note": "string",
            "nicknames": {
                "key": "string"
            },
            "platformIds": [
                "string"
            ],
            "avatar": "string",
            "managedGuildIds": [
                "string"
            ],
            "guildId": "string",
            "defaultWorkspaceId": "string",
            "defaultWorkspaceRecordId": "string",
            "mercenaryGuildIds": [
                "string"
            ],
            "isStreamer": true,
            "matchRecapNotificationsEnabled": true,
            "score": 0,
            "scores": {
                "key": 0
            },
            "performance": {
                "matchesPlayed": 0,
                "averages": {
                    "kills": 0,
                    "killDeathRatio": 0,
                    "deaths": 0,
                    "offense": 0,
                    "defense": 0,
                    "support": 0
                }
            },
            "onboarding": {
                "dashboardSetupCompletedAt": "string",
                "workspaceTourCompletedAt": {
                    "key": "string"
                }
            },
            "createdAt": "string",
            "updatedAt": "string"
        }
    }
} as const
