"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { uploadFileToConvex } from "@/lib/client-uploads";
import { DiscordMarkdownTextarea } from "@/components/app/discord-markdown";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Dictionary } from "@/i18n/dictionaries";
export function ArticleForm({serverId,locale,dictionary}:{serverId:string;locale:string;dictionary:Dictionary}) { const labels=dictionary.articles;const router=useRouter();const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [tags,setTags]=useState("");const [body,setBody]=useState("");const [attachments,setAttachments]=useState<string[]>([]);const [pending,setPending]=useState(false);const [error,setError]=useState(""); async function submit(){setPending(true);setError("");const response=await fetch(`/api/servers/${serverId}/articles`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,description,tags:tags.split(","),body,attachments})});setPending(false);if(response.ok)router.push(`/${locale}/dashboard/servers/${serverId}/articles`);else setError(labels.saveFailed);} return <div className="space-y-4"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder={labels.titlePlaceholder}/><Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={labels.descriptionPlaceholder}/><Input value={tags} onChange={e=>setTags(e.target.value)} placeholder={labels.tagsPlaceholder}/><DiscordMarkdownTextarea value={body} onChange={setBody} placeholder={labels.bodyPlaceholder} height={420}/><input type="file" multiple onChange={async e=>{const files=[...Array.from(e.target.files??[])];setAttachments([...attachments,...await Promise.all(files.map(async file=>(await uploadFileToConvex(file)).url))]);}}/><div className="text-sm">{attachments.map(url=><a key={url} href={url} className="block underline">{url}</a>)}</div>{error?<p className="text-sm text-destructive">{error}</p>:null}<Button disabled={pending} onClick={submit}>{labels.publish}</Button></div>; }
