"use client";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import type { PublicCompetition } from "@/lib/read-models/competitions";
function normalizeName(value: string) { return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase().replace(/[^a-z0-9]+/g, ""); }
export function LinkCompetitionEvent({ serverId, serverName, eventId, competitions }: { serverId: string; serverName: string; eventId: string; competitions: PublicCompetition[] }) {
  const eligible = useMemo(() => competitions.flatMap((competition) => competition.divisions.flatMap((division) => division.teams.filter((team) => normalizeName(team.name) === normalizeName(serverName)).map((team) => ({ competition, division, team })))), [competitions, serverName]);
  const [selectedId, setSelectedId] = useState(eligible[0] ? `${eligible[0].competition.id}:${eligible[0].division.id}:${eligible[0].team.id}` : ""); const [opponentId, setOpponentId] = useState(""); const [ownFirst, setOwnFirst] = useState(true); const [pending, startTransition] = useTransition(); const router = useRouter();
  const selected = eligible.find((entry) => `${entry.competition.id}:${entry.division.id}:${entry.team.id}` === selectedId); if (!selected) return null;
  return <div className="rounded-xl border p-4"><p className="font-medium">Competition match</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={selectedId} onChange={(event) => { setSelectedId(event.target.value); setOpponentId(""); }} className="h-10 rounded-md border bg-transparent px-3">{eligible.map((entry) => <option key={`${entry.competition.id}:${entry.division.id}:${entry.team.id}`} value={`${entry.competition.id}:${entry.division.id}:${entry.team.id}`}>{entry.competition.name} · {entry.division.name}</option>)}</select><select value={opponentId} onChange={(event) => setOpponentId(event.target.value)} className="h-10 rounded-md border bg-transparent px-3"><option value="">Select opponent</option>{selected.division.teams.filter((team) => team.id !== selected.team.id && !team.withdrawn).map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></div><div className="mt-3 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={ownFirst} onChange={(event) => setOwnFirst(event.target.checked)} /> Your clan is Team A</label><Button disabled={!opponentId || pending} onClick={() => startTransition(async () => { const response = await fetch(`/api/servers/${serverId}/events/${eventId}/competition`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ competitionId: selected.competition.id, divisionId: selected.division.id, teamAId: ownFirst ? selected.team.id : opponentId, teamBId: ownFirst ? opponentId : selected.team.id }) }); if (!response.ok) { toast.error("Unable to link competition match."); return; } toast.success("Competition match linked."); router.refresh(); })}>{pending ? "Linking…" : "Link competition match"}</Button></div></div>;
}
